language: swift
osx_image: xcode7
script:
  - xcodebuild -scheme InTune -workspace InTune.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.2' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)

