language: swift
osx_image: xcode10.2

before_install:
 - gem install cocoapods -v '1.6.0'

script:
  - pod install
  - xcodebuild -scheme InTune -workspace InTune.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' build test
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -t bb18b7f1-c811-4c82-af1d-a21d7ef47a44
#  - bash <(curl -s https://codecov.io/bash) -f ./test_reports/cobertura.xml -X coveragepy -X gcov -X xcode

