//
//  ServerResponse.swift
//  InTune
//
//  Created by Ronan on 23/11/2018.
//  Copyright © 2018 Sonomos. All rights reserved.
//
// Generated by https://app.quicktype.io

import Foundation

struct ServerResponse: Codable {
    let resultCount: Int
    let results: [Result]
}

struct Result: Codable {
    let wrapperType: String
    let kind: String
    let artistID, collectionID: Int
    let trackID: Int
    let artistName: String
    let trackName: String
    let artistViewURL, trackViewURL: String
    let previewURL: String
    let artworkUrl30, artworkUrl60, artworkUrl100: String
    let trackPrice: Double
    let releaseDate: Date
    let trackTimeMillis: Int
    let country: String
    let currency: String
    let isStreamable: Bool?
    let shortDescription, longDescription: String?
    
    enum CodingKeys: String, CodingKey {
        case wrapperType, kind
        case artistID = "artistId"
        case collectionID = "collectionId"
        case trackID = "trackId"
        case artistName = "artistName"
        case trackName
        case artistViewURL = "artistViewUrl"
        case trackViewURL = "trackViewUrl"
        case previewURL = "previewUrl"
        case artworkUrl30, artworkUrl60, artworkUrl100
        case trackPrice
        case releaseDate
        case trackTimeMillis, country, currency
        case isStreamable
        case shortDescription, longDescription
    }
}
